server:
  port: 8094
  servlet:    context-path: /
spring:  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ttsx?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: shq184717

#mybatis-plush配置
mybatis-plus:  type-aliases-package: com.ttsx.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  
#引入日志信息
logging:
  level: 
    com.jt.mapper: debug 
#引入dubbo的配置
dubbo:
  scan:
    basePackages: com.ttsx
  application:
    name: provider-cart  #实现同样的接口服务的名称必然相同,不然必然不同 
  registry:
    address: zookeeper://192.168.23.129:2181?backup=192.168.23.129:2182,192.168.23.129:2183
  protocol:
    name: dubbo  # 节点名称
    port: 20881  #相同的服务端口号必然不相同    
    
    
