server:
  port: 8090
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: shq184717
    #如果数据库密码以0开头 使用:""包裹

  mvc:         #引入mvn配置
    view:
      prefix: /WEB-INF/     # /默认代表根目录 src/main/webapp
      suffix: .jsp
mybatis-plus:
    #定义别名包  简化查询resultType配置
  type-aliases-package: com.jt.pojo
  #Mybatis的映射文件路径
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射    字段  属性 对应    去除字段中的"_"之后首字母大写
  configuration:
    map-underscore-to-camel-case: true

  #添加日志
logging:
  level:
    com.jt.mapper: debug 
  
