server:
  port: 8090
  servlet:    context-path: /
spring:  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: shq184717
mybatis:
     #定义别名包简化查询的resulttype配置
  type-aliases-package: com.jt.demo.pojo
  #mybatise的映射文件路径
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射  字段  属性 对应  userId 去除字段中的下划线之后首字母大写
  configuration:
    map-underscore-to-camel-case: true

  
  